
version: '3.8'

services:
  mysql-service:
    image: mysql:8.4
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - mysql-vol:/var/lib/mysql
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 30s

  wordpress-service:
    image: wordpress:6
    container_name: wordpress-container
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql-service
      WORDPRESS_DB_USER: example_user
      WORDPRESS_DB_PASSWORD: example_password
      WORDPRESS_DB_NAME: example_db
    volumes:
      - wordpress-vol:/var/www/html
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 50s
    restart: always
    depends_on:
      mysql-service:
        condition: service_healthy

volumes:
  mysql-vol:
  wordpress-vol:

networks:
  net-wp:
    driver: bridge
